# LLM Configuration
llm:
  provider: "openai"
  model: "gpt-4o"
  max_tokens: 1000
  temperature: 0.7

# Cover Letter Configuration
cover_letter:
  max_length: 400
  tone: "professional"
  style: "concise"

# Output Configuration
output:
  format: "pdf"
  save_to_file: true
  output_dir: "output"

# PDF Configuration
pdf:
  template: "default_template.html"
  template_variables:
    applicant_name: "Your Name"
    applicant_email: "your.email@example.com"
    applicant_phone: "(555) 123-4567"
    applicant_address: "Your Address, City, State ZIP"