# LLM Configuration
llm:
  provider: "openai"
  model: "gpt-4o"
  max_tokens: 1000
  temperature: 0.7

# Cover Letter Configuration
cover_letter:
  max_length: 400
  tone: "professional"
  style: "concise"

# Output Configuration
output:
  format: "text"
  save_to_file: true
  output_dir: "output"