# LLM Configuration
llm:
  provider: "anthropic"  # Options: "openai" or "anthropic"
  model: "claude-3-5-haiku-latest"  # OpenAI models: gpt-4o, gpt-4, gpt-3.5-turbo | Anthropic models: claude-sonnet-4-5, claude-haiku-4-5, claude-3-5-haiku-latest
  max_tokens: 1000
  temperature: 0.7


# Output Configuration
output:
  format: "pdf"
  save_to_file: true
  output_dir: "output"

# Clipboard Configuration
clipboard:
  max_size_bytes: 50000  # 50KB default limit for clipboard content

# PDF Configuration
pdf:
  template: "modern_template.html"
  template_variables:
    applicant_name: "Your Name"
    applicant_email: "youremail@gmail.com"
    applicant_phone: "your number or keep it blank"
    professional_title: "Software Engineer"